"""Fixed-schema check records, scoring, and scorecard rendering (G1-2).

Per-check record shape (CI depends on this — do not change without bumping
schema_version and updating .github workflows):

  { "category": "...", "check": "...", "status": "PASS|WARN|FAIL|N/A",
    "score_impact": 0, "weight": 15, "explanation": "...",
    "evidence_path": "...", "controls": ["PCI-DSS 1.2.1"] }

Score = 100 - sum(score_impact). Grades: A >= 90, B >= 80, C >= 70, D >= 60, else F.
"""

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

SCHEMA_VERSION = 1
STATUSES = {"PASS", "WARN", "FAIL", "N/A"}
REQUIRED_FIELDS = ["category", "check", "status", "score_impact", "weight",
                   "explanation", "evidence_path", "controls"]


def record(category, check, status, weight, explanation, evidence_path, controls,
           warn_factor=0.5):
    """Build one check record. score_impact derives from status:
    FAIL -> weight, WARN -> weight*warn_factor, PASS/N/A -> 0."""
    if status not in STATUSES:
        raise ValueError(f"invalid status {status!r} for check {check!r}")
    impact = {"FAIL": weight, "WARN": round(weight * warn_factor, 1)}.get(status, 0)
    return {
        "category": category, "check": check, "status": status,
        "score_impact": impact, "weight": weight, "explanation": explanation,
        "evidence_path": str(evidence_path), "controls": list(controls),
    }


def validate_record(rec):
    errs = []
    for f in REQUIRED_FIELDS:
        if f not in rec:
            errs.append(f"missing field {f!r}")
    if rec.get("status") not in STATUSES:
        errs.append(f"bad status {rec.get('status')!r}")
    if not isinstance(rec.get("score_impact"), (int, float)):
        errs.append("score_impact not numeric")
    if not isinstance(rec.get("weight"), (int, float)):
        errs.append("weight not numeric")
    if not isinstance(rec.get("controls"), list):
        errs.append("controls not a list")
    return errs


def score(records):
    return max(0, round(100 - sum(r["score_impact"] for r in records), 1))


def grade(s):
    return "A" if s >= 90 else "B" if s >= 80 else "C" if s >= 70 else "D" if s >= 60 else "F"


def source_hash(paths):
    """sha256 over the concatenated bytes of the source inputs, for the
    generated-doc staleness trailer (G1-10)."""
    h = hashlib.sha256()
    for p in sorted(str(p) for p in paths):
        h.update(Path(p).read_bytes())
    return h.hexdigest()


def staleness_trailer(paths):
    return f"<!-- generated-from: sha256:{source_hash(paths)} -->"


def build_report(records, generator, sources):
    return {
        "schema_version": SCHEMA_VERSION,
        "generator": generator,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "source_hash": source_hash(sources),
        "score": score(records),
        "grade": grade(score(records)),
        "totals": {
            "checks": len(records),
            "pass": sum(1 for r in records if r["status"] == "PASS"),
            "warn": sum(1 for r in records if r["status"] == "WARN"),
            "fail": sum(1 for r in records if r["status"] == "FAIL"),
            "na": sum(1 for r in records if r["status"] == "N/A"),
        },
        "checks": records,
    }


def write_report_json(report, path: Path):
    Path(path).write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")


def render_scorecard(report, title, sources):
    s, g = report["score"], report["grade"]
    t = report["totals"]
    lines = [
        f"# {title}",
        "",
        f"Generated by `{report['generator']}` — do not hand-edit. Regenerate with `make score`.",
        "",
        f"**Score: {s} / 100 — Grade {g}**  (PASS {t['pass']} · WARN {t['warn']} · FAIL {t['fail']} · N/A {t['na']})",
        "",
        "| Category | Check | Status | Impact | Weight | Controls |",
        "|---|---|---|---|---|---|",
    ]
    for r in report["checks"]:
        icon = {"PASS": "✅", "WARN": "⚠️", "FAIL": "❌", "N/A": "➖"}[r["status"]]
        lines.append(f"| {r['category']} | {r['check']} | {icon} {r['status']} | "
                     f"-{r['score_impact']} | {r['weight']} | {', '.join(r['controls'])} |")
    lines += ["", "## Explanations", ""]
    for r in report["checks"]:
        if r["status"] in ("FAIL", "WARN"):
            lines.append(f"- **[{r['status']}] {r['category']} / {r['check']}** — "
                         f"{r['explanation']} _(evidence: `{r['evidence_path']}`)_")
    lines += ["", staleness_trailer(sources), ""]
    return "\n".join(lines)
