#!/usr/bin/env python3
"""G1-5/G1-6: Placeholder discipline.

Scans *.tf, *.hcl, *.yaml, *.yml, *.json for PLACEHOLDER_<TYPE>_<NAME> tokens
(GR-4: unknown values become registered tokens, never invented data), and
emits PLACEHOLDERS.md — token -> files table plus how-to-resolve guidance.

Modes:
  python3 scripts/placeholder-scan.py           # regenerate PLACEHOLDERS.md
  python3 scripts/placeholder-scan.py --check   # exit 1 if PLACEHOLDERS.md stale
  python3 scripts/placeholder-scan.py --gate    # exit 1 if ANY token remains
                                                #   (pre-apply gate; allowlist via
                                                #    .github/gate-thresholds.yaml
                                                #    allowed_placeholder_tokens)

Controls: SOC2 CC8.1 (no fabricated config), PCI-DSS 6.4 (change control).
"""

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib import loaders  # noqa: E402

REPO = loaders.REPO_ROOT
OUTPUT = REPO / "PLACEHOLDERS.md"
TOKEN_RE = re.compile(r"PLACEHOLDER_[A-Z0-9_]+")
SCAN_SUFFIXES = {".tf", ".hcl", ".yaml", ".yml", ".json"}
SKIP_DIRS = {".git", ".terragrunt-cache", ".terraform", "evidence", "__pycache__"}

# how-to-resolve guidance per token type (second underscore-delimited field)
RESOLUTIONS = {
    "ACCOUNT": "Resolve from AWS Organizations (`aws organizations list-accounts`) "
               "run by an operator with management-account read access. Never guess "
               "account IDs; the management account itself must never be scanned.",
    "ORG": "Resolve from `gcloud organizations list` (GCP) or "
           "`aws organizations describe-organization` (AWS), run by an org admin.",
    "PROJECT": "Resolve from `gcloud projects describe <project-id> "
               "--format='value(projectNumber)'` after the project exists; project "
               "numbers cannot be known at plan time (see CMEK_WIRING.md workflow).",
    "CIDR": "Resolve from the corporate IPAM / network team. Must not overlap any "
            "range in NETWORK_TOPOLOGY.md; run `make score` (IP Planning) after filling.",
    "KMS": "Resolve after the KMS stacks are applied: copy the key ARN/resource "
           "name from the stack output referenced in the token's file.",
    "CLOUDHSM": "Resolve from the CloudHSM custom key store ID after an operator "
                "provisions it (`aws cloudhsmv2 describe-clusters`).",
    "CORP": "Resolve from the corporate egress IP allocation (network team). Used "
            "for VPC-SC access levels and firewall allowlists.",
}
DEFAULT_RESOLUTION = ("Resolve with the owning team; the token name encodes the "
                      "value type. Never replace with an invented value (GR-4).")


def scan():
    """token -> sorted list of 'path:line' occurrences."""
    found = defaultdict(list)
    for p in sorted(REPO.rglob("*")):
        if not p.is_file() or p.suffix not in SCAN_SUFFIXES:
            continue
        if SKIP_DIRS.intersection(p.relative_to(REPO).parts):
            continue
        try:
            text = p.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for lineno, line in enumerate(text.splitlines(), 1):
            for m in TOKEN_RE.finditer(line):
                found[m.group(0)].append(f"{p.relative_to(REPO)}:{lineno}")
    return dict(sorted(found.items()))


def resolution_for(token):
    parts = token.split("_")
    return RESOLUTIONS.get(parts[1] if len(parts) > 1 else "", DEFAULT_RESOLUTION)


def render(found):
    lines = [
        "# Placeholder Register (G1-5)",
        "",
        "Generated by `scripts/placeholder-scan.py` — do not hand-edit; regenerate",
        "with `make placeholders`. `make placeholder-gate` fails while any token",
        "remains (pre-apply gate, GR-4).",
        "",
    ]
    if not found:
        lines += ["**No placeholder tokens present in the repository.**", ""]
    else:
        lines += [
            f"**{len(found)} distinct tokens, "
            f"{sum(len(v) for v in found.values())} occurrences.**",
            "",
            "| Token | Occurrences |",
            "|---|---|",
        ]
        for tok, locs in found.items():
            lines.append(f"| `{tok}` | {', '.join(f'`{l}`' for l in locs)} |")
        lines += ["", "## How to resolve", ""]
        seen_types = []
        for tok in found:
            ttype = tok.split("_")[1] if len(tok.split("_")) > 1 else "?"
            if ttype in seen_types:
                continue
            seen_types.append(ttype)
            lines += [f"### {ttype}", "", resolution_for(tok), ""]
    return "\n".join(lines) + "\n"


def gate_allowlist():
    """allowed_placeholder_tokens from .github/gate-thresholds.yaml, if present."""
    f = REPO / ".github" / "gate-thresholds.yaml"
    if not f.exists():
        return set()
    data = loaders.load_vars_yaml(f) or {}
    return set(data.get("allowed_placeholder_tokens") or [])


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--gate", action="store_true")
    args = ap.parse_args()

    found = scan()
    content = render(found)

    if args.gate:
        blocked = {t: v for t, v in found.items() if t not in gate_allowlist()}
        if blocked:
            print(f"GATE FAIL: {len(blocked)} unresolved placeholder tokens:",
                  file=sys.stderr)
            for tok, locs in blocked.items():
                print(f"  {tok}: {locs[0]}{' (+more)' if len(locs) > 1 else ''}",
                      file=sys.stderr)
            return 1
        print("GATE OK: no unresolved placeholder tokens")
        return 0

    if args.check:
        if OUTPUT.exists() and OUTPUT.read_text(encoding="utf-8") == content:
            print(f"OK: {OUTPUT.name} is fresh")
            return 0
        print(f"FAIL: {OUTPUT.name} is stale; run make placeholders", file=sys.stderr)
        return 1

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT.name}: {len(found)} tokens")
    return 0


if __name__ == "__main__":
    sys.exit(main())
