#!/usr/bin/env python3
"""G1-9: Generated network topology docs.

Renders NETWORK_TOPOLOGY.md and architecture.mmd from the two vars.yaml files
(single source of truth). Replaces the hand-maintained mermaid block and CIDR
table previously in README.md — README now includes-by-reference.

Both outputs carry a `<!-- generated-from: sha256:... -->` /
`%% generated-from: sha256:...` trailer over the source inputs, checked by
`scripts/validate-docs.py --check-staleness` (G1-10).

Usage:
  python3 scripts/render-topology.py           # write both files
  python3 scripts/render-topology.py --check   # exit 1 if outputs are stale

Controls: PCI-DSS 1.1.2 (current network diagram requirement), SOC2 CC2.1.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib import loaders, report as rp  # noqa: E402

REPO = loaders.REPO_ROOT
TOPOLOGY_MD = REPO / "NETWORK_TOPOLOGY.md"
MERMAID = REPO / "architecture.mmd"
SOURCES = [loaders.AWS_VARS, loaders.GCP_VARS]


def aws_vpcs(aws):
    out = []
    for envkey in sorted(aws.get("Environments", {}) or {}):
        res = (aws["Environments"][envkey] or {}).get("Resources", {}) or {}
        vpc = (res.get("vpc") or {}).get("inputs", {}) or {}
        if not vpc.get("vpc_cidr"):
            continue
        out.append({
            "env": envkey,
            "name": vpc.get("vpc_name", f"{envkey}-vpc"),
            "cidr": vpc["vpc_cidr"],
            "azs": vpc.get("azs", []),
            "private": vpc.get("private_subnets", []),
            "public": vpc.get("public_subnets", []),
            "database": vpc.get("database_subnets", []),
            "intra": vpc.get("intra_subnets", []),
            "elasticache": vpc.get("elasticache_subnets", []),
        })
    return out


def gcp_networks(gcp):
    out = []

    def handle(folder, env, res):
        netvpc = (res.get("net-vpc") or {}).get("inputs", {}) or {}
        subnets = netvpc.get("subnets") or []
        if not subnets:
            return
        sec = netvpc.get("secondary_ranges") or {}
        ranges = []
        for subnet_name, lst in sec.items():
            for r in lst or []:
                ranges.append({"subnet": subnet_name,
                               "name": r.get("range_name"),
                               "cidr": r.get("ip_cidr_range")})
        out.append({
            "folder": folder, "env": env,
            "network": netvpc.get("network_name", "?"),
            "subnets": [{"name": s.get("subnet_name"), "cidr": s.get("subnet_ip"),
                         "region": s.get("subnet_region"),
                         "private_access": s.get("subnet_private_access"),
                         "flow_logs": s.get("subnet_flow_logs")}
                        for s in subnets],
            "secondary": ranges,
            "has_nat": bool(netvpc.get("cloud_nats")),
        })

    for folder, envs in (gcp.get("envs", {}) or {}).items():
        if not isinstance(envs, dict):
            continue
        if "resources" in envs:
            handle(folder, "-", envs.get("resources") or {})
            continue
        for env, envval in envs.items():
            if isinstance(envval, dict) and "resources" in envval:
                handle(folder, env, envval.get("resources") or {})
    return out


def render_markdown(avpcs, gnets):
    lines = [
        "# Network Topology",
        "",
        "Generated by `scripts/render-topology.py` from the two `vars.yaml` files —",
        "do not hand-edit; regenerate with `make topology`. Diagram source:",
        "[architecture.mmd](architecture.mmd).",
        "",
        "## AWS VPCs",
        "",
        "| Env | VPC | CIDR | AZs | Private | Public | Database | Intra | Elasticache |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for v in avpcs:
        lines.append(
            f"| {v['env']} | {v['name']} | `{v['cidr']}` | {len(v['azs'])} | "
            + " | ".join(", ".join(f"`{c}`" for c in v[k]) or "—"
                         for k in ("private", "public", "database", "intra", "elasticache"))
            + " |")
    lines += [
        "",
        "AWS egress today: per-VPC IGW/NAT (no central inspection path — see",
        "`docs/preprod/COVERAGE_MATRIX.md`; G3.A introduces inspection VPCs).",
        "Transit Gateway: `aws/network/tgw` (routes currently hardcoded in hcl).",
        "",
        "## GCP Shared VPC networks",
        "",
        "| Folder/Env | Network | Subnet | CIDR | Region | Private access | Flow logs | Cloud NAT |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for n in gnets:
        for s in n["subnets"]:
            lines.append(
                f"| {n['folder']}/{n['env']} | {n['network']} | {s['name']} | "
                f"`{s['cidr']}` | {s['region']} | "
                f"{'yes' if s['private_access'] else 'NO'} | "
                f"{'yes' if s['flow_logs'] else 'NO'} | "
                f"{'yes' if n['has_nat'] else 'NO'} |")
    lines += ["", "### GKE secondary ranges", "",
              "| Folder/Env | Subnet | Range | CIDR |", "|---|---|---|---|"]
    for n in gnets:
        for r in n["secondary"]:
            lines.append(f"| {n['folder']}/{n['env']} | {r['subnet']} | "
                         f"{r['name']} | `{r['cidr']}` |")
    lines += ["", rp.staleness_trailer(SOURCES), ""]
    return "\n".join(lines) + "\n"


def render_mermaid(avpcs, gnets):
    lines = ["graph TB"]
    lines.append('    subgraph AWS["AWS Landing Zone"]')
    lines.append('        TGW[Transit Gateway]')
    for v in avpcs:
        node = v["env"].replace("-", "_")
        lines.append(f'        {node}["{v["name"]}<br/>{v["cidr"]}"]')
        lines.append(f"        TGW --- {node}")
    lines.append("    end")
    lines.append('    subgraph GCP["GCP Landing Zone"]')
    shared = [n for n in gnets if n["folder"] == "shrd"]
    others = [n for n in gnets if n["folder"] != "shrd"]
    for n in shared:
        node = f'g_{n["folder"]}_{n["env"]}'.replace("-", "_")
        lines.append(f'        {node}["shrd/{n["env"]}: {n["network"]}"]')
    for n in others:
        node = f'g_{n["folder"]}_{n["env"]}'.replace("-", "_")
        lines.append(f'        {node}["{n["folder"]}/{n["env"]}: {n["network"]}"]')
        peer = f'g_shrd_{"prod" if n["folder"] in ("prod", "stg") else "dev"}'
        if any(f'g_{s["folder"]}_{s["env"]}' == peer for s in shared):
            lines.append(f"        {peer} -.peering.- {node}")
    lines.append("    end")
    lines.append(f"    %% generated-from: sha256:{rp.source_hash(SOURCES)}")
    return "\n".join(lines) + "\n"


def build():
    aws = loaders.load_aws_vars()
    gcp = loaders.load_gcp_vars()
    avpcs = aws_vpcs(aws)
    gnets = gcp_networks(gcp)
    return render_markdown(avpcs, gnets), render_mermaid(avpcs, gnets)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    md, mmd = build()

    if args.check:
        ok = (TOPOLOGY_MD.exists() and TOPOLOGY_MD.read_text(encoding="utf-8") == md
              and MERMAID.exists() and MERMAID.read_text(encoding="utf-8") == mmd)
        if ok:
            print("OK: topology docs are fresh")
            return 0
        print("FAIL: topology docs stale; run make topology", file=sys.stderr)
        return 1

    TOPOLOGY_MD.write_text(md, encoding="utf-8")
    MERMAID.write_text(mmd, encoding="utf-8")
    print(f"Wrote {TOPOLOGY_MD.name} and {MERMAID.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
