#!/usr/bin/env python3
"""G4-11: Generate CMEK_WIRING.md — post-apply service-agent key grants.

GCP service agents (service-<PROJECT_NUMBER>@gcp-sa-*.iam.gserviceaccount.com)
require project numbers that do not exist at plan time, so the IAM bindings
cannot be fully declared up front. This renders the exact
`gcloud kms keys add-iam-policy-binding` commands an operator runs once per
stg project after apply, per service agent x key.

Regenerate with `make cmek-wiring`; staleness-checked via the sha256 trailer.

Controls: PCI-DSS 3.5/3.6, CIS GCP 1.10, SOC2 CC6.1.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib import loaders, report as rp  # noqa: E402

REPO = loaders.REPO_ROOT
OUTPUT = REPO / "CMEK_WIRING.md"
SOURCES = [loaders.GCP_VARS]

# service key name -> the service agent(s) that must decrypt with it
SERVICE_AGENTS = {
    "gke": ["service-{n}@container-engine-robot.iam.gserviceaccount.com"],
    "sql": ["service-{n}@gcp-sa-cloud-sql.iam.gserviceaccount.com"],
    "storage": ["service-{n}@gs-project-accounts.iam.gserviceaccount.com"],
    "redis": ["service-{n}@cloud-redis.iam.gserviceaccount.com"],
    "logging": ["service-{n}@gcp-sa-logging.iam.gserviceaccount.com"],
    "pubsub": ["service-{n}@gcp-sa-pubsub.iam.gserviceaccount.com"],
    "bigquery": ["bq-{n}@bigquery-encryption.iam.gserviceaccount.com"],
    "composer": ["service-{n}@cloudcomposer-accounts.iam.gserviceaccount.com"],
}


def stg_kms_envs(gcp):
    """(folder, env, kms_inputs, project_names) for every stg env declaring kms."""
    out = []
    stg = gcp.get("envs", {}).get("stg", {}) or {}
    for env, envval in stg.items():
        if not isinstance(envval, dict):
            continue
        res = envval.get("resources", {}) or {}
        kms = (res.get("kms") or {}).get("inputs")
        if not kms:
            continue
        projects = []
        host = ((res.get("net-vpc") or {}).get("inputs", {}) or {}).get("host_project_name")
        if host:
            projects.append(("host", host))
        svc = ((res.get("svc-projects") or {}).get("inputs", {}) or {})
        base = svc.get("service_project_name")
        for name in (svc.get("service_projects") or {}):
            projects.append((f"service/{name}", f"{base}-{name}" if base else name))
        out.append((("stg", env), kms, projects))
    return out


def render():
    gcp = loaders.load_gcp_vars()
    lines = [
        "# CMEK Wiring (G4-11)",
        "",
        "Post-apply operator commands: grant each GCP service agent",
        "`roles/cloudkms.cryptoKeyEncrypterDecrypter` on its service key.",
        "Generated by `scripts/render-cmek-wiring.py` from `vars.yaml` — do not",
        "hand-edit; regenerate with `make cmek-wiring`.",
        "",
        "Service agents embed the **project number**, which exists only after",
        "the project is created — that is why these grants cannot be fully",
        "declared at plan time. For each project below, first resolve:",
        "",
        "```",
        "PROJECT_NUMBER=$(gcloud projects describe <PROJECT_ID> --format='value(projectNumber)')",
        "```",
        "",
    ]
    envs = stg_kms_envs(gcp)
    if not envs:
        lines.append("**No stg kms configuration found in vars.yaml.**")
    for (folder, env), kms, projects in envs:
        prefix = kms.get("keyring_prefix", "keyring")
        regions = kms.get("regions", [])
        keys = kms.get("keys", {}) or {}
        # the kms stack runs in the env's host project (dependency in its hcl)
        kms_project = next((p for r, p in projects if r == "host"), "<KMS_PROJECT_ID>")
        lines.append(f"## {folder}/{env}")
        lines.append("")
        if not projects:
            lines.append("_No projects resolved from vars — check net-vpc/svc-projects inputs._")
        for role, project in projects:
            lines.append(f"### Project: `{project}` ({role})")
            lines.append("")
            lines.append("```bash")
            lines.append(f"PROJECT_NUMBER=$(gcloud projects describe {project} --format='value(projectNumber)')")
            for region in regions:
                for key in keys:
                    for agent_t in SERVICE_AGENTS.get(key, []):
                        agent = agent_t.format(n="${PROJECT_NUMBER}")
                        lines.append(
                            f"gcloud kms keys add-iam-policy-binding {key} \\\n"
                            f"  --keyring {prefix}-{region} --location {region} \\\n"
                            f"  --project {kms_project} \\\n"
                            f"  --member 'serviceAccount:{agent}' \\\n"
                            f"  --role roles/cloudkms.cryptoKeyEncrypterDecrypter")
            lines.append("```")
            lines.append("")
    lines += [rp.staleness_trailer(SOURCES), ""]
    return "\n".join(lines) + "\n"


def main():
    content = render()
    if "--check" in sys.argv:
        if OUTPUT.exists() and OUTPUT.read_text(encoding="utf-8") == content:
            print("OK: CMEK_WIRING.md fresh")
            return 0
        print("FAIL: CMEK_WIRING.md stale; run make cmek-wiring", file=sys.stderr)
        return 1
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
